{
  "openapi": "3.1.0",
  "info": {
    "title": "Impax Backend - Swagger API",
    "version": "0.1.0",
    "description": "Welcome to ImpaX, where innovation meets the field of sports, prioritizing the well-being of athletes. Our mission is to revolutionize athlete safety through cutting-edge impact monitoring technology.",
    "license": {
      "name": "MIT",
      "url": "https://github.com/cepdnaclk/e19-3yp-impact-tracker/blob/main/LICENSE"
    },
    "contact": {
      "name": "Impax",
      "url": "https://github.com/cepdnaclk/e19-3yp-impact-tracker",
      "email": ""
    }
  },
  "servers": [
    {
      "url": "http://localhost:5000"
    },
    {
      "url": "http://13.235.86.11:5000"
    }
  ],

  "paths": {
    "/auth": {
      "get": {
        "tags": ["AuthEndpoints"],
        "summary": "Authenticate a user - Refresh Token required",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/LoginResponse"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },

    "/team": {
      "post": {
        "tags": ["TeamEndpoints"],
        "summary": "Create a team - Open",
        "requestBody": {
          "$ref": "#/components/requestBodies/TeamCreateRequest"
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/Team"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },

    "/session": {
      "post": {
        "tags": ["SsessionEndpoints"],
        "summary": "Create a session - Access token returned",
        "requestBody": {
          "$ref": "#/components/requestBodies/SessionRequest"
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "message": ""
                }
              }
            }
          }
        },
        "400": {
          "description": "Bad Request",
          "content": {
            "application/json": {
              "example": {
                "message": "Bad Request"
              }
            }
          }
        }
      }
    },

    "/team/manager": {
      "post": {
        "tags": ["TeamEndpoints"],
        "summary": "Create a team for manager - Open",
        "requestBody": {
          "$ref": "#/components/requestBodies/TeamLoginRequest"
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/TeamLoginRequest"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },

    "/team/exists/teamId/{id}": {
      "get": {
        "tags": ["TeamEndpoints"],
        "summary": "Check if a team ID exists - Open",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "exampleTeamId"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/TeamIdExistsResponse"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },

    "/team/{id}": {
      "get": {
        "tags": ["TeamEndpoints"],
        "summary": "Get team details",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "exampleTeamId"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/TeamResponse"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },
    "/team/exists": {
      "get": {
        "tags": ["TeamEndpoints"],
        "summary": "Check if both Team ID and email exists - Open",
        "parameters": [
          {
            "name": "teamId",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "exampleTeamId"
          },
          {
            "name": "email",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "example@example.com"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/TeamIdEmailExistsResponse"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },

    "/manager/exists/email/{email}": {
      "get": {
        "tags": ["ManagerEndpoints"],
        "summary": "Check if a manager email exists - Open",
        "parameters": [
          {
            "name": "email",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "example@example.com"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/ManagerExistsResponse"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },

    "/manager": {
      "post": {
        "tags": ["ManagerEndpoints"],
        "summary": "Create a manager - Open",
        "requestBody": {
          "$ref": "#/components/requestBodies/ManagerCreateRequest"
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/ManagerResponse"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["ManagerEndpoints"],
        "summary": "Get Manager Details",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/ManagerResponse"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },

    "/manager/add": {
      "post": {
        "tags": ["ManagerEndpoints"],
        "summary": "Add a new manager to a team - Access Token required",
        "requestBody": {
          "$ref": "#/components/requestBodies/ManagerTeamRequest"
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/ManagerTeamRequest"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },
    "/accept-invitation/{token}": {
      "get": {
        "tags": ["ManagerEndpoints"],
        "summary": "Accept manager verification",
        "parameters": [
          {
            "name": "token",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "f476d19f-8035-4811-9c40-da0fbe300527"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "example": "Invitation accepted successfully! You can now log in."
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "text/plain": {
                "example": "Invalid or expired token. Please contact support."
              }
            }
          }
        }
      }
    },

    "/player": {
      "post": {
        "tags": ["PlayerEndpoints"],
        "summary": "Create a player",
        "requestBody": {
          "$ref": "#/components/requestBodies/PlayerCreateRequest"
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/PlayerResponse"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },

    "/player/{email}": {
      "get": {
        "tags": ["PlayerEndpoints"],
        "summary": "Get player details",
        "parameters": [
          {
            "name": "email",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "example@example.com"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/PlayerResponse"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },

    "/player/{playerID}/sessions": {
      "get": {
        "tags": ["PlayerEndpoints"],
        "summary": "Get session details related to the player",
        "parameters": [
          {
            "name": "playerID",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "examplePlayerId"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/SessionDetailsResponse"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },

    "/players/{playerID}/total-impacts": {
      "get": {
        "tags": ["PlayerEndpoints"],
        "summary": "Get total impacts for a player",
        "parameters": [
          {
            "name": "playerID",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "examplePlayerId"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/TotalImpactsResponse"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },

    "/highest-impact": {
      "get": {
        "tags": ["PlayerEndpoints"],
        "summary": "Get the highest impact among all records with the date",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/HighestImpactRecord"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },

    "/hub/credetials": {
      "post": {
        "tags": ["HubEndpoints"],
        "summary": "Get hub details - Aceess Token required",
        "requestBody": {
          "$ref": "#/components/requestBodies/HubRequest"
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/HubResponse"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },

    "/hub": {
      "post": {
        "tags": ["HubEndpoints"],
        "summary": "Save hub details - Open",
        "requestBody": {
          "$ref": "#/components/requestBodies/Hub"
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/Hub"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },

    "/login/logout": {
      "post": {
        "tags": ["LoginEndpoints"],
        "summary": "Logout - Access Token required",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "message": "Logout successful"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },

    "/login/manager": {
      "post": {
        "tags": ["LoginEndpoints"],
        "summary": "Login as a manager - Open",
        "requestBody": {
          "$ref": "#/components/requestBodies/LoginRequestManager"
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/LoginResponse"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },

    "/player/add": {
      "post": {
        "tags": ["PlayerEndpoints"],
        "summary": "Add a new player to a team for manager - Access Token required",
        "requestBody": {
          "$ref": "#/components/requestBodies/PlayerTeamRequest"
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/PlayerTeamRequest"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    },

    "/login/player": {
      "post": {
        "tags": ["LoginEndpoints"],
        "summary": "Login as a player - Open",
        "requestBody": {
          "$ref": "#/components/requestBodies/LoginRequest"
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "$ref": "#/components/schemas/LoginResponse"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "Bad Request"
                }
              }
            }
          }
        }
      }
    }
  },

  "security": [
    {
      "bearerAuth": []
    }
  ],

  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "schemas": {
      "LoginRequest": {
        "type": "object",
        "properties": {
          "password": {
            "type": "string"
          },
          "userName": {
            "type": "string"
          }
        },
        "example": {
          "password": "securePassword",
          "userName": "example@example.com"
        }
      },

      "LoginRequestManager": {
        "type": "object",
        "properties": {
          "password": {
            "type": "string"
          },
          "userName": {
            "type": "string"
          },
          "teamId": {
            "type": "string"
          }
        },
        "example": {
          "password": "securePassword",
          "userName": "example@example.com",
          "teamId": "exampleTeamId"
        }
      },

      "TeamLoginRequest": {
        "type": "object",
        "properties": {
          "password": {
            "type": "string"
          },
          "teamId": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          }
        },
        "example": {
          "password": "securePassword",
          "email": "example@example.com",
          "firstName": "John",
          "lastName": "Doe",
          "teamId": "exampleTeamId",
          "teamName": "TeamName"
        }
      },

      "SessionRequest": {
        "type": "object",
        "properties": {
          "sessionId": {
            "type": "string"
          },
          "teamId": {
            "type": "string"
          },
          "sessionName": {
            "type": "string"
          },
          "createdAt": {
            "type": "integer"
          },
          "updatedAt": {
            "type": "integer"
          },
          "impactHistory": {
            "type": "string"
          }
        },
        "example": {
          "sessionId": "sessionId",
          "sessionName": "sessionName",
          "createdAt": 486486,
          "updatedAt": 486486,
          "teamId": "exampleTeamId",
          "impactHistory": {
            "12": [
              {
                "magntitude": 10,
                "direction": "left",
                "timestamp": 123456789,
                "isConcussion": true
              }
            ],
            "13": [
              {
                "magntitude": 10,
                "direction": "left",
                "timestamp": 123456789,
                "isConcussion": false
              }
            ]
          }
        }
      },

      "HubRequest": {
        "type": "object",
        "properties": {
          "hubId": {
            "type": "string"
          },
          "hubKey": {
            "type": "string"
          }
        },
        "example": {
          "hubId": "exampleHubId",
          "hubKey": "exampleHubKey"
        }
      },

      "HubResponse": {
        "type": "object",
        "properties": {
          "mqttUsername": {
            "type": "string"
          },
          "mqttPassword": {
            "type": "string"
          },
          "mqttCA": {
            "type": "string"
          }
        },
        "example": {
          "mqttUsername": "exampleUsername",
          "mqttPassword": "examplePassword",
          "mqttCA": "exampleCA"
        }
      },

      "Hub": {
        "type": "object",
        "properties": {
          "mqttUsername": {
            "type": "string"
          },
          "mqttPassword": {
            "type": "string"
          },
          "mqttCA": {
            "type": "string"
          },
          "hubKey": {
            "type": "string"
          },
          "hubId": {
            "type": "string"
          }
        },
        "example": {
          "mqttUsername": "exampleUsername",
          "mqttPassword": "examplePassword",
          "mqttCA": "exampleCA",
          "hubKey": "exampleHubKey",
          "hubId": "exampleHubId"
        }
      },

      "ManagerTeamRequest": {
        "type": "object",
        "properties": {
          "managerEmail": {
            "type": "string"
          },
          "teamId": {
            "type": "string"
          }
        },
        "example": {
          "managerEmail": "example@example.com",
          "teamId": "teamId"
        }
      },

      "PlayerTeamRequest": {
        "type": "object",
        "properties": {
          "playerEmail": {
            "type": "string"
          },
          "teamId": {
            "type": "string"
          }
        },
        "example": {
          "playerEmail": "example@example.com",
          "teamId": "teamId"
        }
      },

      "LoginResponse": {
        "type": "object",
        "properties": {
          "refreshToken": {
            "type": "string"
          },
          "accessToken": {
            "type": "string"
          }
        },
        "example": {
          "refreshToken": "abcd",
          "accessToken": "abcd"
        }
      },

      "ManagerExistsResponse": {
        "type": "object",
        "properties": {
          "managerExists": {
            "type": "boolean"
          }
        },
        "example": {
          "managerExists": true
        }
      },

      "ManagerCreateRequest": {
        "type": "object",
        "properties": {
          "teamId": {
            "type": "string"
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "teamId": "exampleTeamId",
          "firstName": "John",
          "lastName": "Doe",
          "email": "example@example.com",
          "password": "securePassword"
        }
      },

      "ManagerResponse": {
        "type": "object",
        "properties": {
          "teamId": {
            "type": "string"
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "email": {
            "type": "string"
          }
        },
        "example": {
          "teamId": "exampleTeamId",
          "firstName": "John",
          "lastName": "Doe",
          "email": "example@example.com"
        }
      },

      "TeamIdExistsResponse": {
        "type": "object",
        "properties": {
          "teamExists": {
            "type": "boolean"
          }
        },
        "example": {
          "teamExists": true
        }
      },
      "TeamManagerInterface": {
        "type": "object",
        "properties": {
          "teamId": {
            "type": "string"
          },
          "email": {
            "type": "string"
          }
        },
        "example": {
          "teamId": "exampleTeamId",
          "email": "example@example.com"
        }
      },
      "TeamIdEmailExistsResponse": {
        "type": "object",
        "properties": {
          "teamExists": {
            "type": "boolean"
          },
          "managerExists": {
            "type": "boolean"
          }
        },
        "example": {
          "teamExists": true,
          "managerExists": false
        }
      },

      "Team": {
        "type": "object",
        "properties": {
          "teamId": {
            "type": "string"
          },
          "teamName": {
            "type": "string"
          },
          "teamManager": {
            "type": "string"
          }
        },
        "example": {
          "teamId": "exampleTeamId",
          "teamName": "Example Team",
          "teamManager": "example@example.com"
        }
      },

      "TeamResponse": {
        "type": "object",
        "properties": {
          "teamId": {
            "type": "string"
          },
          "teamName": {
            "type": "string"
          }
        },
        "example": {
          "teamId": "exampleTeamId",
          "teamName": "Example Team"
        }
      },

      "PlayerCreateRequest": {
        "type": "object",
        "properties": {
          "playerId": {
            "type": "string"
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "teams": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "example": {
          "playerId": "examplePlayerId",
          "firstName": "John",
          "lastName": "Doe",
          "email": "example@example.com",
          "password": "securePassword",
          "address": "123 Main St",
          "teams": ["Team1", "Team2"]
        }
      },

      "PlayerResponse": {
        "type": "object",
        "properties": {
          "playerId": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "teams": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "example": {
          "playerId": "12345",
          "email": "example@example.com",
          "firstName": "John",
          "lastName": "Doe",
          "address": "123 Main St",
          "teams": ["Team1", "Team2"]
        }
      },

      "SessionDetailsResponse": {
        "type": "object",
        "properties": {
          "sessionId": {
            "type": "string"
          },
          "date": {
            "type": "string",
            "format": "date"
          },
          "startTime": {
            "type": "string",
            "format": "time"
          },
          "endTime": {
            "type": "string",
            "format": "time"
          },
          "location": {
            "type": "string"
          },
          "hostManagerId": {
            "type": "string"
          },
          "players": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "example": {
          "sessionId": "12345",
          "date": "2023-01-01",
          "startTime": "10:00:00",
          "endTime": "12:00:00",
          "location": "Field 1",
          "hostManagerId": "host123",
          "players": ["player1", "player2"]
        }
      },

      "TotalImpactsResponse": {
        "type": "object",
        "properties": {
          "playerId": {
            "type": "string"
          },
          "totalImpacts": {
            "type": "integer"
          }
        },
        "example": {
          "playerId": "12345",
          "totalImpacts": 1000
        }
      },

      "HighestImpactRecord": {
        "type": "object",
        "properties": {
          "sessionId": {
            "type": "string"
          },
          "date": {
            "type": "string",
            "format": "date"
          },
          "highestImpact": {
            "type": "number"
          }
        },
        "example": {
          "sessionId": "12345",
          "date": "2023-01-01",
          "highestImpact": 10.5
        }
      }
    },

    "requestBodies": {
      "TeamCreateRequest": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Team"
            }
          }
        }
      },

      "PlayerCreateRequest": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/PlayerCreateRequest"
            }
          }
        }
      },

      "ManagerTeamRequest": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ManagerTeamRequest"
            }
          }
        }
      },

      "SessionRequest": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/SessionRequest"
            }
          }
        }
      },

      "Hub": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Hub"
            }
          }
        }
      },

      "PlayerTeamRequest": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/PlayerTeamRequest"
            }
          }
        }
      },

      "TeamLoginRequest": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/TeamLoginRequest"
            }
          }
        }
      },

      "HubRequest": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HubRequest"
            }
          }
        }
      },

      "LoginRequest": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/LoginRequest"
            }
          }
        }
      },

      "LoginRequestManager": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/LoginRequestManager"
            }
          }
        }
      },

      "LoginResponse": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/LoginResponse"
            }
          }
        }
      },

      "ManagerCreateRequest": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ManagerCreateRequest"
            }
          }
        }
      },

      "TeamIdEmailCheckRequest": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/TeamManagerInterface"
            }
          }
        }
      }
    }
  }
}
